# coroot compose config
# overrides DCAPE/apps/drone/dcape-app/docker-compose.yml

services:
  app:
    profiles: ["server", "all"]
    command:
      - '--data-dir=/data'
      - '--bootstrap-prometheus-url=${P8S_ADDR}'
      - '--bootstrap-refresh-interval=${REFRESH_INTERVAL}'
      - '--bootstrap-clickhouse-address=${CH_ADDR}'
    environment:
      - PG_CONNECTION_STRING=postgres://${PGUSER}:${PGPASSWORD}@db/${PGDATABASE}?sslmode=disable
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${APP_ROOT}/data:/data

  agent:
    image: ${AGENT_IMAGE}:${AGENT_IMAGE_VER}
    profiles: ["agent", "all"]
    command:
      - '--collector-endpoint=${COLLECTOR}'
      - '--cgroupfs-root=/host/sys/fs/cgroup'
      - '--wal-dir=/data'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /sys/kernel/tracing:/sys/kernel/tracing
      - /sys/kernel/debug:/sys/kernel/debug
      - /sys/fs/cgroup:/host/sys/fs/cgroup
      - ${APP_ROOT}/node_data:/data
    pid: host
    privileged: true
    labels:
      - "prometheus.io/scrape=true"
      - "prometheus.io/port=80"
      - "prometheus.io/extra-labels=job:coroot-node-agent"
    restart: always
