# app custom Makefile

# Docker repo & image name without version
IMAGE    ?= ghcr.io/coroot/coroot
# Hostname for external access
APP_SITE ?= coroot.dev.lan
# App names (db/user name etc)
APP_NAME ?= coroot

# PgSQL used as DB
USE_DB = yes

# Sample admin user data
ADD_USER = no

# ------------------------------------------------------------------------------
# app custom config

IMAGE_VER       ?= 0.14.5

DCAPE_ROOT      ?= /opt/dcape/var

DATA_PATH        ?= $(APP_NAME)

CONTAINER_ID ?= $(APP_TAG)_app_1

# ------------------------------------------------------------------------------
# .env template (custom part)
# inserted in .env.sample via 'make config'
define CONFIG_CUSTOM
# ------------------------------------------------------------------------------
# app custom config, generated by make config
# db:$(USE_DB) user:$(ADD_USER)

# Path to /opt/dcape/var. Used only outside drone
DCAPE_ROOT=$(DCAPE_ROOT)

DATA_PATH=$(DATA_PATH)

endef

# ------------------------------------------------------------------------------
# Find and include DCAPE/apps/drone/dcape-app/Makefile
DCAPE_COMPOSE   ?= dcape-compose
DCAPE_MAKEFILE  ?= $(shell docker inspect -f "{{.Config.Labels.dcape_app_makefile}}" $(DCAPE_COMPOSE))
ifeq ($(shell test -e $(DCAPE_MAKEFILE) && echo -n yes),yes)
  include $(DCAPE_MAKEFILE)
else
  include /opt/dcape-app/Makefile
endif

stat-user:
# \c - postgres
# create extension pg_stat_statements;
# grant pg_monitor to coroot;


addon:
	x=$(shell $(MAKE) -n add &> /dev/null) ; [ "$x" ] || echo "none"
